### PR TITLE
Report specific model error on load failure

### LINKED ISSUE #50: Report specific error message on failed load
Having ALDB output a more meaningful error message upon a failed load saves the user the effort of having to cross-check with the Alloy Analyzer for the exact issue with their model.

### PR DESCRIPTION
**Pull request by liangdrew**
Having ALDB output a more meaningful error message upon a failed load saves the user the effort of having to cross-check with the Alloy Analyzer for the exact issue with their model.

From the Analyzer:
image

In ALDB:
```
(aldb) load ../DigitalWatch.als
Reading model from ../DigitalWatch.als...error.

Syntax error:
File cannot be found.
/<path>/<to>/<dir>/util/ctl.als (No such file or directory)
(aldb)
```

```
(aldb) load ../DigitalWatch.als
Reading model from ../DigitalWatch.als...error.

Syntax error in /<path>/<to>/<dir>/DigitalWatch.als at line 1499 column 21:
The name "imp_" cannot be found.
(aldb)
```

Note that sections I've marked as "internal errors" should only be reached due to misimplementation on our end or rare fatal errors (for example, I/O).

Relevant Alloy code paths: [(1)](https://github.com/AlloyTools/org.alloytools.alloy/blob/1da30a1b2003b7fc95822b81d0094cc14a2e25ae/org.alloytools.alloy.core/src/main/java/edu/mit/csail/sdg/alloy4/ErrorSyntax.java#L59) [(2)](https://github.com/AlloyTools/org.alloytools.alloy/blob/master/org.alloytools.alloy.core/src/main/java/edu/mit/csail/sdg/parser/CompUtil.java#L361)

Closes #50.

### CODE REVIEW

**Comment by pxlcoder** [comment]
Two comments on the output.

I loaded a model with a syntax error (an extra closing brace) and was shown the following output:

```
(aldb) load models/test.als
Reading model from models/test.als...syntax error. There are 5 possible tokens that can appear here:
enum fun let open pred
(aldb)
```

1. I think we should print the error message on a separate line (with an additional blank line) for readability. 

```
(aldb) load models/test.als
Reading model from models/test.als...syntax error.

There are 5 possible tokens that can appear here:
enum fun let open pred
(aldb)
```

2. I think we should display the line number of position of the error, as done in the Analyzer. In the previous output, the user would still need to open the Analyzer to find the source of their issue. This information can be obtained through the following [public field](https://github.com/AlloyTools/org.alloytools.alloy/blob/master/org.alloytools.alloy.core/src/main/java/edu/mit/csail/sdg/alloy4/Err.java#L31).

**Comment by liangdrew** [comment]
@pxlcoder for 1) – sure, that sounds fine to me. As for 2), keep in mind that we are compiling the temp Alloy model that we augment. As such, reporting the line position of the error in the temp file may be misleading. Thoughts?

**Comment by pxlcoder** [comment]
@liangdrew I don't think what you described is an issue, since your implementation reports the error at the beginning of `initializeWithModel`, where we compile the original model.

File: src/simulation/SimulationManager.java [hunk 1]
```diff
@@ -429,8 +440,16 @@ public String getWorkingDirPath() {
     }
 
     private boolean initializeWithModel(File model) {
-        if (AlloyInterface.compile(model.getPath()) == null) {
-            System.out.println("error. Could not parse model.");
+        try {
+            AlloyInterface.compile(model.getPath());
+        } catch (Err e) {
```
Comment (LaRenegaws) [inline src/simulation/SimulationManager.java:465]: Can we catch the specific errors here instead of catching a generic alloy error and then breaking it down.

**Comment by liangdrew** [comment]
@pxlcoder ah you're right. I was recalling output I previously saw at a different failure spot during development. I'll make that change.

File: src/simulation/SimulationManager.java [hunk 2]
```diff
@@ -452,6 +471,12 @@ private boolean initializeWithModel(File model) {
             }
         }
 
+        int transRelIndex = modelString.indexOf(String.format("pred %s", getParsingConf().getTransitionRelationName()));
```
Comment (LaRenegaws) [inline src/simulation/SimulationManager.java:503]: Do we need to do this check for the `stateSigName` as well since we are already doing it for the `transitionRelationName` and `initPredicateName`.

Comment (liangdrew) [reply src/simulation/SimulationManager.java:503]: No, that error would be caught earlier as a syntax error if the sig name used in the `init` and/or `next` pred is not defined.

File: src/simulation/SimulationManager.java [hunk 3]
```diff
@@ -172,13 +178,21 @@ public boolean performStep(int steps, List<String> constraints) {
...
 
-        A4Solution sol = AlloyInterface.run(compModule);
+        A4Solution sol = null;
+        try {
+            sol = AlloyInterface.run(compModule);
+        } catch (Err e) {
+            System.out.println("Cannot perform step. Internal error.");
+            return false;
+        }
         if (sol == null || !sol.satisfiable()) {
```
Comment (pxlcoder) [inline src/simulation/SimulationManager.java]: Do we still need to null-check `sol`?

File: src/simulation/SimulationManager.java [hunk 4]
```diff
@@ -268,12 +282,19 @@ public boolean performUntil(int limit) {
...
             }
 
-            A4Solution sol = AlloyInterface.run(compModule);
+            A4Solution sol = null;
+            try {
+                sol = AlloyInterface.run(compModule);
+            } catch (Err e) {
+                return false;
+            }
             if (sol == null) {
```
Comment (pxlcoder) [inline src/simulation/SimulationManager.java]: Null-check might not be necessary.

File: src/simulation/SimulationManager.java [hunk 5]
```diff
@@ -324,13 +345,21 @@ public boolean setToInit() {
...
         }
 
-        A4Solution sol = AlloyInterface.run(compModule);
+        A4Solution sol = null;
+        try {
+            sol = AlloyInterface.run(compModule);
+        } catch (Err e) {
+            System.out.println("internal error.");
+            return false;
+        }
```
Comment (pxlcoder) [inline src/simulation/SimulationManager.java:362]: Nit: Newline after closing brace.

File: src/simulation/SimulationManager.java [hunk 6]
```diff
@@ -507,13 +559,21 @@ private boolean initializeWithModel(File model) {
...
         }
 
-        A4Solution sol = AlloyInterface.run(compModule);
+        A4Solution sol = null;
+        try {
+            sol = AlloyInterface.run(compModule);
+        } catch (Err e) {
+            System.out.printf("error.\n\n%s\n", e.msg.trim());
+            return false;
+        }
```
Comment (pxlcoder) [inline src/simulation/SimulationManager.java:577]: Nit: Newline after closing brace.

File: src/simulation/SimulationManager.java (hunk 3 above)
Comment (liangdrew) [reply src/simulation/SimulationManager.java]: I don't think we have any situations where the input CompModule has no commands, so I think the answer is no.

File: src/alloy/AlloyInterface.java [hunk 7]
```diff
@@ -27,19 +27,12 @@
...
-
-        return null;
+    public static CompModule compile(String modelPath) throws Err {
+        return CompUtil.parseEverything_fromFile(reporter, null, modelPath);
     }
 
-    public static A4Solution run(CompModule module) {
+    public static A4Solution run(CompModule module) throws Err {
         List<Command> commands = module.getAllCommands();
-        if (commands.isEmpty()) {
```
Comment (pxlcoder) [inline src/alloy/AlloyInterface.java:40]: While this case doesn't occur due to our injected command, this class is independent from the rest of the code, and I feel it shouldn't make any assumptions about its use.

Maybe we can throw `Err` if the list is empty?

Comment (liangdrew) [reply src/alloy/AlloyInterface.java:40]: Actually, I don't think that should be a concern for us at all due to [the default command](https://github.com/AlloyTools/org.alloytools.alloy/blob/master/org.alloytools.alloy.core/src/main/java/edu/mit/csail/sdg/parser/CompUtil.java#L452) that is always injected into `CompModule`s.

**Review by pxlcoder — APPROVED** [review]

**Review by aman-dureja — APPROVED** [review]
