### PR TITLE
Simplify parsing of trace to A4Solution

### LINKED ISSUE #54: Loading a trace fails when the instance imports symlinked modules
When an XML instance is created with the Alloy Analyzer using an Alloy model with imported modules referring to symlinks, loading the trace fails in ALDB.

### PR DESCRIPTION
**Pull request by liangdrew**
As per the [documentation](http://alloytools.org/documentation/alloy-api/edu/mit/csail/sdg/alloy4compiler/translator/A4SolutionReader.html#read(java.lang.Iterable,%20edu.mit.csail.sdg.alloy4.XMLNode)) for `A4SolutionReader.read`, "_if there's a sig or field X in the XML but not in the list, then X (and its value in XML file) is added to the solution_". As a result, the error-prone file manipulation logic we use in order to get a `CompModule` from `parseEverything_fromFile` is not necessary.

Fixes #54.

### CODE REVIEW

File: src/simulation/SimulationManager.java [hunk 1]
```diff
@@ -607,7 +607,13 @@ private boolean initializeWithTrace(File trace) {
         A4Solution sol;
         try {
             sol = AlloyInterface.solutionFromXMLFile(trace);
-        } catch (Exception e) {
+        } catch (Exception ex) {
+            if (ex instanceof Err) {
```
Comment (pxlcoder) [inline src/simulation/SimulationManager.java]: You should be able to avoid `instanceof` and the cast by using:

```
try {
} catch (Err err) {
} catch (Exception e) {
}
```

**Review by pxlcoder — APPROVED** [review]
Nice work!

**Review by LaRenegaws — APPROVED** [review]
